### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by mikbr** [LopeKinz/ByeBye-Bitcoin-Remaster#4]
changed URL to https://keys.qcoinz.com/bitcoin/random then ran the program. this is what i got back.

Installing required packages...
Requirement already satisfied: beautifulsoup4==4.9.3 in c:\users\mb341\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 1)) (4.9.3)
Requirement already satisfied: requests==2.31.0 in c:\users\mb341\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\mb341\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4==4.9.3->-r requirements.txt (line 1)) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mb341\appdata\local\programs\python\python311\lib\site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mb341\appdata\local\programs\python\python311\lib\site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mb341\appdata\local\programs\python\python311\lib\site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mb341\appdata\local\programs\python\python311\lib\site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (2023.7.22)
Running the script...
Traceback (most recent call last):
  File "C:\Users\MB341\ByeBye-Bitcoin-Remaster\main.py", line 64, in <module>
    process_wallet(wallet)
  File "C:\Users\MB341\ByeBye-Bitcoin-Remaster\main.py", line 22, in process_wallet
    if "Private Key" in getwallet:
                        ^^^^^^^^^
NameError: name 'getwallet' is not defined. Did you mean: 'wallet'?
Script execution completed.
Press any key to exit...

**Comment by Zecxy** [comment]
i tried this aswell, changed 'getwallet' to 'wallet' and now its supposidly checking the wallets

**Comment by Zecxy** [comment]
i can see at the top the wallet checked number is increasing, so i assume its working, unsure as of yet

**Comment by Jamestee007** [comment]
Change  line 22, in if "Private Key" in getwallet:  to  if "Private Key" in wallet: would get resolved

**Comment by SuperKaa** [comment]
the api does not work anymore, bitcoinlist.io is down and qcoinz.com is returning errors, do you have any new site to use?
